# File: docker-compose.yml

version: "3"
services:
  # Dokumentation: https://github.com/timche/docker-csgo-updater
  csgo_updater:
    container_name: "csgo_updater"
    # timches Updater Image
    image: "timche/csgo-updater"
    restart: "unless-stopped"
    # kann auch isoliert laufen, network_mode ist aber einfacher
    network_mode: "host"
    volumes:
      # notwendig um via Socket Docker Befehle (wie einen Neustart) zu senden
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      # Container mit dem folgenden Image werden berücksichtigt
      UPDATER_CONTAINER_IMAGE: "timche/csgo"
      # Interval (Sekunden) in denen Container gescannt werden
      UPDATER_POLL_INTERVAL: 60

  csgo_practice:
    container_name: "csgo_practice"
    # fertiges Image mit Training-Plugin
    image: "timche/csgo:pug-practice"
    restart: "unless-stopped"
    network_mode: "host"
    volumes:
      - "/srv/docker/containers/csgo_practice/:/home/csgo/server:rw"
    env_file:
      - practice.env
